# Site
repository: SathiyamV/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sathiya Sundaram V
title: Fresher
email: sathiyamsharmila@gmail.com
website: sathiyam-resume.netlify.app

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  SathiyamV
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: sathiyam.v
linkedin_username: sathiyasundaramv
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
 - title: resume
   icon: fas fa-globe
   url: https://www.canva.com/design/DAFj_LYpD18/tKOzhqJahjMSpkU_IPOBNw/view?utm_content=DAFj_LYpD18&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/pic.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name Sathiya Sundaram V and I'm a Fresher. Final Year B.sc student pursuing Computer science, Good with the fundamentals of Frontend and Backend Development. Technically sound with concepts of JavaScript & Python. I actively pursue and educate myself with the latest available technology.

  I am most skilled in: <mark>JavaScript</mark> and <mark>Web Development</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Simple Portfolio Website
        link: https://portsat.netlify.app
        link_text: Portfolio Website
        additional_links:
          - title:  portfolio
            icon: fab fa-github
            url: github.com/SathiyamV/portfolio
        quote: >
          I Started to learn Frontend From this Project.
          
      - layout: top-middle
        title: Google.com Clone
        link: https://sat-googleclone.netlify.app
        link_text: google.com
        additional_links:
          - title:  Gooleclone
            icon: fab fa-github
            url: github.com/SathiyamV/googleclone
        quote: >
          Build FrontEnd of Google.com page .    
      
      - layout: top-middle
        title: DigitalCard Site
        link: https://sat-digitalcard.netlify.app
        link_text: DigitalCard Site
        additional_links:
          - title:  Digitalcard
            icon: fab fa-github
            url: github.com/SathiyamV/Digital-Card-Scrimba
        quote: >
          Simple Digital card with Animation.
      
      - layout: top-middle
        title: Birthday Gift Site
        link: https://jaider-20.netlify.app
        link_text: Birthday Gift site
        additional_links:
          - title:  Birthdaygift
            icon: fab fa-github
            url: github.com/SathiyamV/jaiderbdaygift
        quote: >
          Created Birthday gift site For my Friend.
      
      - layout: top-middle
        title: HomeTownPage
        link: https://sat-solopro1.netlify.app
        link_text: HometownPage
        additional_links:
          - title:  HometownPage
            icon: fab fa-github
            url: github.com/SathiyamV/Module-2-Solo-project-Scrimba
        quote: >
          Build Hometown site using figma design and Finished the Project.
      - layout: top-middle
        title: Streaming site Email-Template
        link: https://sat-streamingsite.netlify.app
        link_text: Steaming site Template
        additional_links:
          - title:  Streaming site
            icon: fab fa-github
            url: github.com/SathiyamV/Streaming-template
          
        quote: >
          Build a email template only using html and internal css.    
      
      - layout: top-middle
        title: Social Email Template
        link: https://sat-emailtemplate.netlify.app
        link_text: Social Email Template
        additional_links:
         - title:  Social Email template
           icon: fab fa-github
           url: https://github.com/SathiyamV/email-template
        quote: >
          Build a email template only using html and internal css.
      
      - layout: top-middle
        title: Passenger counter app
        link: https://passcount-sat.netlify.app
        link_text: PassengerCounterApp
        additional_links:
          - title:  passengerCounterapp
            icon: fab fa-github
            url: github.com/SathiyamV/passenger-counter-js
        quote: >
          Build an Interactive Passenger counter app using HTML, CSS & JS .
      
      - layout: top-middle
        title: Basketball Scoreboard
        link: https://sat-basketballscoreboard.netlify.app
        link_text: BasketballScoreBoard
        additional_links:
          - title:  BasketballScoreBoard
            icon: fab fa-github
            url: github.com/SathiyamV/basketball-scoreboard
        quote: >
          Build an Interactive Basketball Scoreboard using HTML, CSS & JS .

      - layout: top-middle
        title: Blackjack Game
        link: https://sat-blackjack.netlify.app
        link_text: BlackjackGame
        additional_links:
          - title:  BlackjackGame
            icon: fab fa-github
            url: github.com/SathiyamV/Blackjack_game
        quote: >
          Build an Interactive BlackJack Game using HTML, CSS & JS .

      - layout: top-middle
        title: Password Generator
        link: https://sat-passwordgenerator.netlify.app
        link_text: PasswordGenerator
        additional_links:
          - title:  PasswordGenerator
            icon: fab fa-github
            url: github.com/SathiyamV/password_generator
        quote: >
          Build an Interactive BlackJack Game using HTML, CSS & JS .    

      - layout: top-middle
        title: Travel Site Landing Page
        link: https://sat-traveling-landing-page.netlify.app
        link_text: TravelSiteLandingPage
        additional_links:
          - title:  TravelSiteLandingPage
            icon: fab fa-github
            url: github.com/SathiyamV/Travel-landing-page    
        quote: >
          Its My Full Fledged project Build From Scratch.
      
      - layout: top-middle
        title: Lead Tracker
        link: https://sat-leadtracker.netlify.app
        link_text: LeadTracker
        additional_links:
          - title:  LeadTracker
            icon: fab fa-github
            url: github.com/SathiyamV/lead-tracker    
        quote: >
          Build an Chrome Extension using JavaScript and played with LocalStorage.
      
      - layout: top-middle
        title: Web Drum
        link: https://sat-jsdrum.netlify.app
        link_text: WebDrum
        additional_links:
          - title:  WebDrum
            icon: fab fa-github
            url: github.com/SathiyamV/javascript-drum    
        quote: >
          Build an Interactive Web Drum Using JS EventListener.


      - layout: top-middle
        title: Todo Application
        # link: github.com/SathiyamV
        # link_text: Project Website
        additional_links:
          - title:  todoapp
            icon: fab fa-github
            url: github.com/SathiyamV/fastapi
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          I learned about backend and API about in this Project .
          
          
  - title: Skills
    layout: text
    content: |
      My Technical Skills are:
      - Frontend Languages : HTML, CSS, JavaScript
      - Programming Languages : Python, Java, C++,C
      - Frontend Library : React JS
      - Database : MYSQL, Sqlite
      - Version Control : Git, GitHub
      - Computer Networks
 # - title: Skills
   # layout: text
   # content:    
     # - layout: left
       # title: Programming Languages
       # sub_title: Python, Java, C++,C
     # - layout: left
       # title: Backend Frameworks
       # sub_title: Fast API, Django 
     # - layout: left
       # title: Computer Networks
     # - layout: left
       # title: Frontend Languages
       # sub_title: HTML, CSS, JavaScript
     # - layout: left
       # title: Frontend Framework
       # sub_title: Bootstrap
     # - layout: left
       # title: Frontend Library
       # sub_title: React JS
     # - layout: left
       # title: Database
       # sub_title: MYSQL,Sqlite
     # - layout: left
       # title: Version Control
       # sub_title: Git, GitHub
   # - title: Experience # Title for the section
   # layout: list # Type of content section (list/text)
   # content:
     # - layout: left
       # title: The Boring Company
       # link: boringcompany.com
       # link_text: boringcompany.com
       # sub_title: Senior Network System Administrator
       # caption: November 2017 - Present
       # quote: >
         # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
       # description: | # this will include new lines to allow paragraphs
          # Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Sri Krishna Adithiya College of Arts and Science
        caption: 2021 - 2024
        sub_title: BSc Computer Science
      - layout: top-middle
        title: Sri Vidya Matric Higher Secondary School,Virudhunagar
        caption: 2020 - 2021
        sub_title: HSC
        sub_title: 80%
      - layout: top-middle
        title: KVS Higher Secondary School,Virudhunagar
        caption: 2018 - 2019
        sub_title: SSLC
        sub_title: 70%
       # quote: >
         # Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
       # description: | # this will include new lines to allow paragraphs
         # During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

         # I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Reading Books
      - Watching Movies,Series and Anime
      - Gaming
      - Listening Music and Singing
      - Playing Keyboard

     

# Footer
footer_show_references: true
references_title: Â©Copyright Free

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
